apiVersion: geofront.nerv.com/v1alpha1
kind: Eva
metadata:
  labels:
    app.kubernetes.io/name: smooth-operator
    app.kubernetes.io/managed-by: kustomize
  name: eva-sample-failing
spec:
  image: "nginx:latest"
  color: "purple"
  pilot: "Shinji Ikari"
  command:
    - /bin/sh
    - -c
    - "echo 'Eva unit activating...'; sleep 10; echo 'Eva unit malfunction!'; exit 1"
