apiVersion: geofront.nerv.com/v1alpha1
kind: Eva
metadata:
  labels:
    app.kubernetes.io/name: smooth-operator
    app.kubernetes.io/managed-by: kustomize
  name: eva-sample
spec:
  image: "nginx:latest"
  color: "red"
  pilot: "Asuka Langley Soryu"
  

  # TODO(user): Add fields here
