apiVersion: geofront.nerv.com/v1alpha1
kind: Eva
metadata:
  labels:
    app.kubernetes.io/name: smooth-operator
    app.kubernetes.io/managed-by: kustomize
  name: eva-sample-invalid-image
spec:
  image: "nonexistent/image:does-not-exist"
  color: "black"
  pilot: "Rei Ayanami"
